//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 11:04:57 AM CEST 
//


package rent.app.controller.ws.generate;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for priceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="priceRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pricePerDay" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="insurancePrice" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="distanceOverflowPrice" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(namespace = "http://uns.ac.rs/xml/team18")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "priceRequest", propOrder = {
    "id",
    "token",
    "name",
    "pricePerDay",
    "insurancePrice",
    "distanceOverflowPrice",
    "discount",
    "deleted"
})
public class PriceRequest {

    protected long id;
    @XmlElement(required = true)
    protected String token;
    @XmlElement(required = true)
    protected String name;
    protected float pricePerDay;
    protected float insurancePrice;
    protected float distanceOverflowPrice;
    protected float discount;
    protected boolean deleted;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pricePerDay property.
     * 
     */
    public float getPricePerDay() {
        return pricePerDay;
    }

    /**
     * Sets the value of the pricePerDay property.
     * 
     */
    public void setPricePerDay(float value) {
        this.pricePerDay = value;
    }

    /**
     * Gets the value of the insurancePrice property.
     * 
     */
    public float getInsurancePrice() {
        return insurancePrice;
    }

    /**
     * Sets the value of the insurancePrice property.
     * 
     */
    public void setInsurancePrice(float value) {
        this.insurancePrice = value;
    }

    /**
     * Gets the value of the distanceOverflowPrice property.
     * 
     */
    public float getDistanceOverflowPrice() {
        return distanceOverflowPrice;
    }

    /**
     * Sets the value of the distanceOverflowPrice property.
     * 
     */
    public void setDistanceOverflowPrice(float value) {
        this.distanceOverflowPrice = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public float getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(float value) {
        this.discount = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

}
